package io.github.yumika;

enum TokenType {
  // Single-character tokens.
  LEFT_BRACKET, RIGHT_BRACKET,
  LEFT_PAREN, RIGHT_PAREN,
  LEFT_BRACE, RIGHT_BRACE,
  COMMA, COLON, DOT, MINUS, PLUS,
  PIPE, SEMICOLON, SLASH, STAR,

  // One or two character tokens.
  BANG, BANG_EQUAL,
  EQUAL, EQUAL_EQUAL,
  GREATER, GREATER_EQUAL,
  LESS, LESS_EQUAL,

  // Literals.
  IDENTIFIER, STRING, NUMBER,

  // Keywords.
  AND, AS, CLASS, ELSE, FALSE, FUN, FOR, IF, IN, IMPORT, OR, NULL,
  PRINT, RETURN, SUPER, THIS, TRUE, UNDEFINED, VAR, WHILE,

  EOF
}
