package io.github.yumika;

public enum TokenType {
  // Single-character tokens.
  LEFT_BRACKET, RIGHT_BRACKET,
  LEFT_PAREN, RIGHT_PAREN,
  LEFT_BRACE, RIGHT_BRACE,
  COMMA, COLON, DOT, MINUS, PLUS,
  PIPE, SEMICOLON, SLASH, STAR, STAR_STAR,

  // One, two, or three character tokens.
  ARROW, AT, BACKTICK,
  BANG, BANG_EQUAL,
  DOT_DOT_DOT,
  EQUAL, EQUAL_EQUAL,
  GREATER, GREATER_EQUAL,
  LESS, LESS_EQUAL,
  MINUS_EQUAL, MINUS_MINUS,
  PLUS_EQUAL, PLUS_PLUS,
  PERCENT, QUESTION,
  QUESTION_DOT, QUESTION_QUESTION,
  TEMPLATE_STRING,

  // Literals.
  FALSE, TRUE, IDENTIFIER, STRING, NUMBER,

  // Keywords.
  AND, AS, CASE, CATCH, CLASS, ELSE, FUN, FOR, GET, IF, IN, IMPORT, INTERFACE,
  MATCH, NEW, NOT, NULL, OR, PRINT, PUTS, RETURN, SET, SUPER,
  THIS, THROW, TRY, TYPE, UNDEFINED, VAR, WHEN, WHILE,

  EOF
}
